//! `review/duplicate-helper` detector — near-duplicate function bodies
//! introduced in the diff (normalized-AST-token Jaccard >= 0.85).
//!
//! ## Algorithm (06-RESEARCH.md § Code Examples "MinHash-LSH sketch")
//! For every function-like node in every already-parsed [`ReviewFile`] tree:
//!  1. extract its NORMALIZED token sequence — leaf tokens with every
//!     identifier collapsed to `ID`, every string to `STR`, every number to
//!     `NUM`, structural tokens (`if`/`(`/`{`/operators/keywords) verbatim;
//!  2. skip anything below [`MIN_NORMALIZED_TOKENS`] (A5, LOCKED — filters
//!     getters / one-line arrow callbacks that would otherwise flood findings);
//!  3. build the k=[`SHINGLE_K`] shingle SET (each shingle a truncated sha2
//!     content sketch — non-cryptographic, no security property depends on it,
//!     Security Domain V6 n/a);
//!  4. keep the [`MINHASH_N`] smallest shingle values as a MinHash sketch.
//!
//! Candidate pairs are generated by LSH bucketing (two functions sharing any
//! MinHash value) so the comparison is near-linear, never O(n^2) (threat
//! T-06-08). Each candidate pair's EXACT Jaccard is recomputed over the full
//! shingle sets; a pair fires [`review/duplicate-helper`] when Jaccard >=
//! [`JACCARD_THRESHOLD`] AND at least one side is INTRODUCED (containment,
//! per `super::is_introduced_declaration`). Each introduced function reports
//! at most once (its first qualifying partner in stable order — DEC-01).
//!
//! This file is the ONLY thing 06-03 rewrites for this rule; `review/mod.rs`
//! is never touched (Wave 3 stays parallel with 06-04).

use std::collections::{BTreeSet, HashMap, HashSet};

use getdev_grammars::tree_sitter::{Node, Query};
use sha2::{Digest, Sha256};

use super::{is_introduced_declaration, ReviewFile};
use crate::findings::{Confidence, Finding, Severity};
use crate::scan::Lang;

/// Exact-Jaccard fire threshold (A2, LOCKED). A near-duplicate is a
/// maintainability nudge, never a bug — hence `low`/`medium` below.
const JACCARD_THRESHOLD: f64 = 0.85;
/// Minimum normalized-token length before a function is even a candidate
/// (A5, LOCKED) — below this, getters / one-liners produce meaningless
/// "duplicates".
const MIN_NORMALIZED_TOKENS: usize = 20;
/// Shingle (k-gram) width over the normalized token sequence.
const SHINGLE_K: usize = 5;
/// How many of the smallest shingle values form the MinHash-LSH sketch used
/// for candidate bucketing.
const MINHASH_N: usize = 4;

/// One fingerprinted function-like node.
struct FnRecord {
    rel: String,
    line: u32,
    column: u32,
    end_line: u32,
    is_introduced: bool,
    shingles: HashSet<u64>,
    minhash: Vec<u64>,
}

/// Detect introduced near-duplicate helper functions.
pub(crate) fn detect(files: &[ReviewFile]) -> Vec<Finding> {
    let records = fingerprint_functions(files);
    if records.len() < 2 {
        return Vec::new();
    }

    // LSH bucket: MinHash value -> the functions that carry it. Two functions
    // sharing >= 1 value become a candidate pair (near-linear, not O(n^2)).
    let mut buckets: HashMap<u64, Vec<usize>> = HashMap::new();
    for (idx, rec) in records.iter().enumerate() {
        for &h in &rec.minhash {
            buckets.entry(h).or_default().push(idx);
        }
    }

    let mut findings = Vec::new();
    let mut reported: HashSet<usize> = HashSet::new();

    // Stable order: records are in (file order, source order); each introduced
    // function reports at most once, on its first qualifying partner.
    for i in 0..records.len() {
        if !records[i].is_introduced || reported.contains(&i) {
            continue;
        }
        let mut candidates: BTreeSet<usize> = BTreeSet::new();
        for &h in &records[i].minhash {
            if let Some(list) = buckets.get(&h) {
                for &j in list {
                    if j != i {
                        candidates.insert(j);
                    }
                }
            }
        }
        for &j in &candidates {
            let similarity = jaccard(&records[i].shingles, &records[j].shingles);
            if similarity >= JACCARD_THRESHOLD {
                findings.push(duplicate_finding(&records[i], &records[j], similarity));
                reported.insert(i);
                break;
            }
        }
    }

    findings
}

/// Fingerprint every candidate function-like node across all files, in a
/// deterministic (file order, then source order) sequence.
fn fingerprint_functions(files: &[ReviewFile]) -> Vec<FnRecord> {
    let mut records = Vec::new();
    for file in files {
        let Ok(query) = Query::new(&file.lang.language(), function_query(file.lang)) else {
            continue;
        };
        let bytes = file.source.as_bytes();
        let mut nodes = crate::audit::run_ast_matcher(&query, file.tree.root_node(), bytes);
        // Source order — determinism regardless of tree-sitter match order.
        nodes.sort_by_key(getdev_grammars::tree_sitter::Node::start_byte);
        for node in nodes {
            let mut tokens = Vec::new();
            collect_normalized_tokens(node, &mut tokens);
            if tokens.len() < MIN_NORMALIZED_TOKENS {
                continue;
            }
            let shingles = shingle_set(&tokens);
            if shingles.is_empty() {
                continue;
            }
            let minhash = minhash_sketch(&shingles);
            let start = node.start_position();
            let end = node.end_position();
            let start_line = u32::try_from(start.row)
                .unwrap_or(u32::MAX)
                .saturating_add(1);
            let end_line = u32::try_from(end.row).unwrap_or(u32::MAX).saturating_add(1);
            records.push(FnRecord {
                rel: file.rel.clone(),
                line: start_line,
                column: u32::try_from(start.column)
                    .unwrap_or(u32::MAX)
                    .saturating_add(1),
                end_line,
                is_introduced: is_introduced_declaration(
                    (start_line, end_line),
                    &file.added_ranges,
                ),
                shingles,
                minhash,
            });
        }
    }
    records
}

/// The function-like node kinds review fingerprints — the exact set
/// `scan::function_query` uses (reproduced here because scan's query is
/// module-private).
fn function_query(lang: Lang) -> &'static str {
    match lang {
        Lang::JavaScript | Lang::TypeScript | Lang::Tsx => {
            "(function_declaration) @fn\n\
             (function_expression) @fn\n\
             (arrow_function) @fn\n\
             (method_definition) @fn"
        }
        Lang::Python => "(function_definition) @fn",
    }
}

/// Walk a node's descendant LEAF tokens into a normalized sequence: every
/// identifier -> `ID`, every string -> `STR`, every number -> `NUM`, comments
/// dropped, and every other terminal (keyword / punctuation / operator) kept
/// verbatim via its tree-sitter kind (an anonymous node's `kind()` IS its
/// literal source text).
fn collect_normalized_tokens(node: Node<'_>, out: &mut Vec<String>) {
    match node.kind() {
        "identifier"
        | "property_identifier"
        | "shorthand_property_identifier"
        | "shorthand_property_identifier_pattern"
        | "type_identifier" => {
            out.push("ID".to_owned());
            return;
        }
        "string" | "template_string" => {
            out.push("STR".to_owned());
            return;
        }
        "number" | "integer" | "float" => {
            out.push("NUM".to_owned());
            return;
        }
        "comment" => return,
        _ => {}
    }
    let count = node.child_count();
    if count == 0 {
        // Terminal structural token — keyword / punctuation / operator.
        out.push(node.kind().to_owned());
        return;
    }
    for i in 0..count {
        if let Some(child) = node.child(i) {
            collect_normalized_tokens(child, out);
        }
    }
}

/// The k=[`SHINGLE_K`] shingle set: each shingle a truncated sha2 hash of a
/// k-gram window (a non-cryptographic content sketch).
fn shingle_set(tokens: &[String]) -> HashSet<u64> {
    let mut set = HashSet::new();
    for window in tokens.windows(SHINGLE_K) {
        set.insert(shingle_hash(&window.join(" ")));
    }
    set
}

/// Truncate a sha2 digest to a `u64` similarity-sketch value.
fn shingle_hash(gram: &str) -> u64 {
    let digest = Sha256::digest(gram.as_bytes());
    let mut head = [0u8; 8];
    head.copy_from_slice(&digest[..8]);
    u64::from_le_bytes(head)
}

/// MinHash sketch = the [`MINHASH_N`] smallest shingle values, sorted.
fn minhash_sketch(shingles: &HashSet<u64>) -> Vec<u64> {
    let mut values: Vec<u64> = shingles.iter().copied().collect();
    values.sort_unstable();
    values.truncate(MINHASH_N);
    values
}

/// Exact Jaccard similarity over two full shingle sets.
fn jaccard(a: &HashSet<u64>, b: &HashSet<u64>) -> f64 {
    if a.is_empty() && b.is_empty() {
        return 0.0;
    }
    let intersection = a.iter().filter(|x| b.contains(*x)).count();
    let union = a.len() + b.len() - intersection;
    if union == 0 {
        0.0
    } else {
        intersection as f64 / union as f64
    }
}

/// Build the `review/duplicate-helper` finding, anchored on the INTRODUCED
/// function `anchor` and naming its duplicate partner `other` in `detail`
/// (SPEC-RULES heuristic-detail requirement — confidence != high).
fn duplicate_finding(anchor: &FnRecord, other: &FnRecord, similarity: f64) -> Finding {
    let percent = (similarity * 100.0).round() as u32;
    Finding {
        id: "review/duplicate-helper".to_owned(),
        command: "review".to_owned(),
        severity: Severity::Low,
        confidence: Confidence::Medium,
        file: anchor.rel.clone(),
        line: Some(anchor.line),
        column: Some(anchor.column),
        end_line: Some(anchor.end_line),
        message: "Introduced helper is a near-duplicate of an existing function".to_owned(),
        detail: Some(format!(
            "~{percent}% token-similar to {}:{} (normalized-AST fingerprint, heuristic; \
             confidence: medium) — consider extracting a single shared helper",
            other.rel, other.line
        )),
        suggestion: None,
        remediation: Some(
            "extract the shared logic into one reusable helper instead of a near-copy".to_owned(),
        ),
        fixable: false,
        refs: vec!["https://getdev.ai/rules/review/duplicate-helper".to_owned()],
        fingerprint: None,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use getdev_grammars::tree_sitter::Parser;

    fn review_file(
        rel: &str,
        lang: Lang,
        source: &str,
        added_ranges: Vec<(u32, u32)>,
        is_new_file: bool,
    ) -> ReviewFile {
        let mut parser = Parser::new();
        parser.set_language(&lang.language()).unwrap();
        let tree = parser.parse(source, None).unwrap();
        ReviewFile {
            rel: rel.to_owned(),
            lang,
            source: source.to_owned(),
            tree,
            added_ranges,
            is_new_file,
        }
    }

    // Two structurally identical >=20-token functions (only identifiers
    // differ, so they normalize to the same token stream).
    const INTRODUCED_FN: &str = "\
function computeTotal(items) {
  let total = 0;
  for (let i = 0; i < items.length; i++) {
    total += items[i].price * items[i].quantity;
  }
  return total;
}
";
    const EXISTING_FN: &str = "\
function sumOrders(orders) {
  let sum = 0;
  for (let j = 0; j < orders.length; j++) {
    sum += orders[j].price * orders[j].quantity;
  }
  return sum;
}
";

    #[test]
    fn near_identical_pair_with_one_introduced_fires_once() {
        let introduced = review_file(
            "src/new.js",
            Lang::JavaScript,
            INTRODUCED_FN,
            vec![(1, 8)],
            true,
        );
        // added_ranges empty => this function is NOT introduced.
        let existing = review_file("src/old.js", Lang::JavaScript, EXISTING_FN, vec![], false);
        let findings = detect(&[introduced, existing]);
        assert_eq!(findings.len(), 1, "exactly one duplicate finding expected");
        assert_eq!(findings[0].id, "review/duplicate-helper");
        assert_eq!(
            findings[0].file, "src/new.js",
            "anchored on the introduced side"
        );
        assert_eq!(findings[0].severity, Severity::Low);
        assert_eq!(findings[0].confidence, Confidence::Medium);
        assert!(findings[0].detail.as_ref().unwrap().contains("src/old.js"));
    }

    #[test]
    fn sub_twenty_token_duplicates_are_skipped() {
        // Identical, but far below the 20-token floor.
        let a = review_file(
            "a.js",
            Lang::JavaScript,
            "const g = () => 1 + 2 + 3;\n",
            vec![(1, 1)],
            true,
        );
        let b = review_file(
            "b.js",
            Lang::JavaScript,
            "const h = () => 1 + 2 + 3;\n",
            vec![(1, 1)],
            true,
        );
        assert!(
            detect(&[a, b]).is_empty(),
            "min-size guard must suppress trivial duplicates"
        );
    }

    #[test]
    fn dissimilar_functions_do_not_fire() {
        let other = "\
function parseConfig(raw) {
  const parsed = JSON.parse(raw);
  if (!parsed.name) {
    throw new Error(\"missing name field in config\");
  }
  return parsed.name.toUpperCase();
}
";
        let a = review_file(
            "src/new.js",
            Lang::JavaScript,
            INTRODUCED_FN,
            vec![(1, 8)],
            true,
        );
        let b = review_file("src/other.js", Lang::JavaScript, other, vec![(1, 8)], true);
        assert!(
            detect(&[a, b]).is_empty(),
            "dissimilar functions must not fire"
        );
    }

    #[test]
    fn duplicate_with_neither_introduced_is_gated_out() {
        // Both real duplicates, but neither lies inside an added range.
        let a = review_file("src/one.js", Lang::JavaScript, INTRODUCED_FN, vec![], false);
        let b = review_file("src/two.js", Lang::JavaScript, EXISTING_FN, vec![], false);
        assert!(
            detect(&[a, b]).is_empty(),
            "a duplicate where neither side is introduced must produce zero findings"
        );
    }
}
